#!/usr/bin/env bash
# Usage: jenv completions <command> [arg1 arg2...]

set -e
[ -n "$JENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  jenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "jenv-$COMMAND" || command -v "jenv-sh-$COMMAND")"
if grep -i "^# provide jenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
