#!/usr/bin/env bash
# Summary: Remove all JDK installations
# Usage: jenv remove-all
set -e
[ -n "$JENV_DEBUG" ] && set -x

for path in "${JENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    JENV_VERSION=${path##*/}
    rm -f $path
    rm -f ${JENV_ROOT}/$JENV_VERSION.time
    echo "JDK $JENV_VERSION removed"
  fi
done

$(jenv-rehash)
