#!/usr/bin/env bash
set -e
[ -n "$JENV_DEBUG" ] && set -x



JENV_VERSION="$1" 
JENV_JAVAPATH="$2"
JENV_VERSION_FILE=".jenv-version"

                            
if [ -f "$JENV_JAVAPATH/bin/java" ];
then
 	ln -s  "$JENV_JAVAPATH" "${JENV_ROOT}/versions/$JENV_VERSION"         
	$(jenv-rehash)
else
	echo "$JENV_JAVAPATH is not a valid path to java installation"
fi
