#!/usr/bin/env bash
#
# Summary: Display path to selected JAVA_HOME
#
# Usage: jenv javahome
#
set -e
[ -n "$JENV_DEBUG" ] && set -x

exportVariable(){
   exportedValues="$exportedValues:$1"
   export "$1"="$2"
}

# Provide jenv completions
if [ "$1" = "--complete" ]; then
  echo "--detail"
fi

export JENV_VERSION
JENV_VERSION="$(jenv-version-name)"

export JENV_OPTIONS="$(jenv-options)"

export JAVA_HOME
if [ "$JENV_VERSION" != "system" ]; then
  JAVA_HOME="$JENV_ROOT/versions/$JENV_VERSION"
fi

if [ "$1" = "--detail" ]; then
  echo "$JENV_VERSION" "$JAVA_HOME"
else
  echo "$JAVA_HOME"
fi
