#!/usr/bin/env bash
# Summary: Explain how the current Ruby version is set
set -e
[ -n "$JENV_DEBUG" ] && set -x

if [ -n "$JENV_VERSION" ]; then
  echo "JENV_VERSION environment variable"
else
  jenv-version-file
fi
