#!/usr/bin/env bash
set -e
[ -n "$JENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: jenv completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "jenv-$COMMAND" || command -v "jenv-sh-$COMMAND")"
if grep -i "^# provide jenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
