#!/usr/bin/env bash
set -e
[ -n "$JENV_DEBUG" ] && set -x

# Provide jenv completions
if [ "$1" = "--complete" ]; then
  exec jenv-versions --bare
fi

JENV_VERSION="$1" 
                  
                            
if [ -L " " ];
then         
	rm -f $JENV_ROOT/versions/$JENV_VERSION
  $(jenv-rehash)

else
	echo "$JENV_VERSION is not a managed version of Java "
fi
