#!/usr/bin/env bash
#
# Summary: Set or show the global Maven version
#
# Usage: jenv mvn-global <version>
#
# Sets the global Maven version. You can override the global version at
# any time by setting a directory-specific version with `jenv mvn-local'
# or by setting the `JENV_MAVEN_VERSION' environment variable.
#
# <version> should be a string matching a Maven version known to jenv.
# The special version string `system' will use your default system Maven.
# Run `jenv mvn-versions' for a list of available Maven versions.

set -e
[ -n "$JENV_DEBUG" ] && set -x

# Provide jenv completions
if [ "$1" = "--complete" ]; then  
  echo --unset
  echo system      
  exec jenv-mvn-versions --bare
fi

JENV_MAVEN_VERSION="$1"
JENV_MAVEN_VERSION_FILE="${JENV_ROOT}/maven-version"
      

if [ "$JENV_MAVEN_VERSION" = "--unset" ]; then
  rm -f "${JENV_ROOT}/maven-version"
elif [ -n "$JENV_MAVEN_VERSION" ]; then
  jenv-version-file-write "$JENV_MAVEN_VERSION_FILE" "$JENV_MAVEN_VERSION"
else
  jenv-version-file-read "$JENV_MAVEN_VERSION_FILE" ||
  jenv-version-file-read "${JENV_ROOT}/global" ||
  jenv-version-file-read "${JENV_ROOT}/default" ||
  echo system
fi
