#!/usr/bin/env bash
#
# Summary: Display path to selected JAVA_HOME
#
# Usage: jenv javahome
#
set -e
[ -n "$JENV_DEBUG" ] && set -x      


exportVariable(){   
echo $exportedValues
   exportedValues="$exportedValues:$1"
   export $1="$2 $3 $4 $5 $6 $7 $8 $9"
}

# Provide jenv completions
if [ "$1" = "--complete" ]; then
  exec jenv shims --short
fi

export JENV_VERSION="$(jenv-version-name)"


export JENV_OPTIONS="$(jenv-options)"    

resolve_link() {
  $(type -p greadlink readlink | head -1) $@
}

javaHome="$JENV_ROOT/versions/$JENV_VERSION"
# try to detect system jdk/jre
if [ "$JENV_VERSION" = "system" ] && [ ! -e "$javaHome" ]; then
  systemJava=$(resolve_link -f /usr/bin/javac)
  if [ -e "$systemJava" ]; then
    javaHome="${systemJava%%/bin/javac}"
  else
    systemJava=$(resolve_link -f /usr/bin/java)
    if [ -e "$systemJava" ]; then
      javaHome="${systemJava%%/bin/java}"
    fi
  fi
fi

export JAVA_HOME="$javaHome" 

echo $JAVA_HOME