#!/usr/bin/env bash
#
# Summary: Show information about which command will be executed
#
# Usage: jenv info <command>
#


set -e
[ -n "$JENV_DEBUG" ] && set -x     
            


exportVariable(){   
   exportedKey[$1]=$1; 
   exportedValue[$2]=$2;
   export $1=$2 
}

# Provide jenv completions
if [ "$1" = "--complete" ]; then
  exec jenv shims --short
fi

export JENV_VERSION="$(jenv-version-name)"    
            
export JENV_OPTIONS="$(jenv-options)"    


JENV_COMMAND="$1"              

export JAVA_HOME="$JENV_ROOT/versions/$JENV_VERSION"    
                



JENV_COMMAND_PATH="$(jenv-which "$JENV_COMMAND")"
JENV_BIN_PATH="${JENV_COMMAND_PATH%/*}"


for script in $(jenv-hooks exec); do
  source "$script"
done

shift 1
if [ "$JENV_VERSION" != "system" ]; then
  export PATH="${JENV_BIN_PATH}:${PATH}"
fi
echo "Jenv will exec : $JENV_COMMAND_PATH" $JENV_OPTIONS "$@"             
echo "Exported variables : "
for i in "${!exportedKey[@]}"
do
  key="${exportedKey[$i]}"    
  value=${exportedValue[$key]} 
  echo "$key=$value"
done
