#!/usr/bin/env bash
# Summary: List existing jenv shims
# Usage: jenv shims [--short]

set -e
[ -n "$JENV_DEBUG" ] && set -x

# Provide jenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

for command in "${JENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
