#!/usr/bin/env bash
set -e
[ -n "$JENV_DEBUG" ] && set -x

# Provide jenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec jenv-versions --bare
fi

if [ -n "$1" ]; then
  export JENV_VERSION="$1"
elif [ -z "$JENV_VERSION" ]; then
  JENV_VERSION="$(jenv-version-name)"
fi

if [ "$JENV_VERSION" = "system" ]; then
  RUBY_PATH="$(jenv-which ruby)"
  echo "${RUBY_PATH%/*}"
  exit
fi

JENV_PREFIX_PATH="${JENV_ROOT}/versions/${JENV_VERSION}"
if [ ! -d "$JENV_PREFIX_PATH" ]; then
  echo "jenv: version \`${JENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$JENV_PREFIX_PATH"
