#!/usr/bin/env bash
# Summary: Explain how the current Java version is set
set -e
[ -n "$JENV_DEBUG" ] && set -x

if [ -n "$JENV_OPTIONS" ]; then
  echo "JENV_OPTIONS environment variable"
else
  jenv-options-file
fi
