#!/usr/bin/env bash
# Summary: Show the current Maven version
set -e
[ -n "$JENV_DEBUG" ] && set -x

if [ -z "$JENV_MAVEN_VERSION" ]; then
  JENV_MAVEN_VERSION_FILE="$(jenv-mvn-version-file)"
  JENV_MAVEN_VERSION="$(jenv-version-file-read "$JENV_MAVEN_VERSION_FILE" || true)"
fi

if [ -z "$JENV_MAVEN_VERSION" ] || [ "$JENV_MAVEN_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${JENV_ROOT}/maven-versions/${version}" ]
}

if version_exists "$JENV_MAVEN_VERSION"; then
  echo "$JENV_MAVEN_VERSION"
else
  echo "jenv: version \`$JENV_MAVEN_VERSION' is not installed" >&2
  exit 1
fi
