#!/usr/bin/env bash
# Summary: Show the current Java version and its origin
#
# Shows the currently selected Java version and how it was
# selected. To obtain only the version string, use `jenv
# version-name'.

set -e
[ -n "$JENV_DEBUG" ] && set -x

echo "$(jenv-version-name) (set by $(jenv-version-origin))"
