#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Ruby version
#
# Usage: jenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Ruby
# version's `bin' directory is at the front.
#
# For example, if the currently selected Ruby version is 1.9.3-p327:
#   jenv exec bundle install
#
# is equivalent to:
#   PATH="$JENV_ROOT/versions/1.9.3-p327/bin:$PATH" bundle install

set -e
[ -n "$JENV_DEBUG" ] && set -x

# Provide jenv completions
if [ "$1" = "--complete" ]; then
  exec jenv shims --short
fi

export JENV_VERSION="$(jenv-version-name)"
JENV_COMMAND="$1"

if [ -z "$JENV_COMMAND" ]; then
  jenv-help --usage exec >&2
  exit 1
fi

JENV_COMMAND_PATH="$(jenv-which "$JENV_COMMAND")"
JENV_BIN_PATH="${JENV_COMMAND_PATH%/*}"

for script in $(jenv-hooks exec); do
  source "$script"
done

shift 1
if [ "$JENV_VERSION" != "system" ]; then
  export PATH="${JENV_BIN_PATH}:${PATH}"
fi
exec -a "$JENV_COMMAND" "$JENV_COMMAND_PATH" "$@"
